export const jwt = {
  CLIENT_SECRET: process.env.CLIENT_SECRET,
  CLIENT_EXPIRES_IN: process.env.CLIENT_EXPIRES_IN,
  DELIVERYMAN_SECRET: process.env.DELIVERYMAN_SECRET,
  DELIVERYMAN_EXPIRES_IN: process.env.DELIVERYMAN_EXPIRES_IN,
};
